name: Linux
on:
  push:
  pull_request:
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        label:
          - AlmaLinux 8
        include:
          - label: AlmaLinux 8
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
          run: |
        - name: Test with docker
          run: |
            cd test
            rake ${{matrix.id}}:test
