name: Linux
on:
  push:
  pull_request:
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        label:
          - AlmaLinux 8
        include:
          - label: AlmaLinux 8
            test-docker-image: almalinux:8
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Test
          run: |
            docker run \
              --rm \
              --volume ${PWD}:/Groonga-HTTP:ro \
              ${{ matrix.test-docker-image }} \
              /Groonga-HTTP/t/run-test.sh
