name: Package
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  schedule:
    - cron: |
        0 0 * * *
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Install dependencies
          run: |
            sudo apt -y install software-properties-common
            sudo add-apt-repository -y universe
            sudo add-apt-repository -y ppa:groonga/ppa
            sudo apt update
            sudo apt -V install \
              cpanminus \
              groonga \
              groonga-token-filter-stem \
              groonga-tokenizer-mecab \
              perl
            sudo cpanm -n --with-recommends Minilla
        - name: Start Groonga HTTP server for tests
          run: |
            rm -rf db
            mkdir db
            cat t/fixture/*.grn > dump.grn
            groonga -n db/db < dump.grn
        - name: Build package
          run: |
            groonga --protocol http -s db/db &
            minil dist
            echo "module_version=`cat docs/_config.yml | grep version | awk '{print $2}'`" >> $GITHUB_ENV
        # Artifact
        - uses: actions/upload-artifact@v2
          with:
            name: Groonga-HTTP-${{ env.module_version }}
            path: Groonga-HTTP-${{ env.module_version }}.tar.gz
        # Release
        - name: Upload to release
          uses: softprops/action-gh-release@v1
          if: |
            startsWith(github.ref, 'refs/tags/')
          with:
            files: |
              Groonga-HTTP-${{ env.module_version }}.tar.gz

